services:
  dev:
    build: 
      context: .
      args:
        UID: ${UID}
        GID: ${GID}

    volumes:
      - .:/app/dev
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    ports:
      - "5432:5432"