// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreateUserData.sql

package db

import (
	"context"
)

const createUserData = `-- name: CreateUserData :one
INSERT INTO users (
username, 
email, 
password) 
VALUES ($1, $2, $3)
RETURNING id, username, email, password
`

type CreateUserDataParams struct {
	Username string
	Email    string
	Password string
}

func (q *Queries) CreateUserData(ctx context.Context, arg CreateUserDataParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserData, arg.Username, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}
