// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreateRefreshToken.sql

package db

import (
	"context"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_token(
user_id, token)
VALUES ( $1, $2 )
RETURNING id, user_id, token
`

type CreateRefreshTokenParams struct {
	UserID int32  `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.Token)
	var i RefreshToken
	err := row.Scan(&i.ID, &i.UserID, &i.Token)
	return i, err
}
