// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreatePostForUser.sql

package db

import (
	"context"
)

const createPostForUser = `-- name: CreatePostForUser :one
INSERT INTO text_posts(
title, content, user_id, username)
VALUES ($1,$2,$3, $4)
RETURNING id, user_id, title, content, username, created_at
`

type CreatePostForUserParams struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	UserID   int32  `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) CreatePostForUser(ctx context.Context, arg CreatePostForUserParams) (TextPost, error) {
	row := q.db.QueryRow(ctx, createPostForUser,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.Username,
	)
	var i TextPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}
