// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreateTodo.sql

package db

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todo_list(
  user_id, project_id, title
) VALUES ($1, $2, $3)
RETURNING id, project_id, user_id, title, completed, created_at, updated_at
`

type CreateTodoParams struct {
	UserID    int32  `json:"user_id"`
	ProjectID int32  `json:"project_id"`
	Title     string `json:"title"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.UserID, arg.ProjectID, arg.Title)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
