// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreateToDoListProject.sql

package db

import (
	"context"
)

const createToDoListProject = `-- name: CreateToDoListProject :one
INSERT INTO projects_todo_list(
    user_id, title
) VALUES ($1, $2)
RETURNING id, user_id, title, created_at
`

type CreateToDoListProjectParams struct {
	UserID int32  `json:"user_id"`
	Title  string `json:"title"`
}

func (q *Queries) CreateToDoListProject(ctx context.Context, arg CreateToDoListProjectParams) (ProjectsTodoList, error) {
	row := q.db.QueryRow(ctx, createToDoListProject, arg.UserID, arg.Title)
	var i ProjectsTodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}
