// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreateTodo.sql

package db

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todo_list(
   project_id, title, description
) VALUES ($1, $2, $3)
RETURNING id, project_id, title, description, completed, created_at, updated_at
`

type CreateTodoParams struct {
	ProjectID   int32  `json:"project_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.ProjectID, arg.Title, arg.Description)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
