// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: DeleteToDoByID.sql

package db

import (
	"context"
)

const deleteToDoByID = `-- name: DeleteToDoByID :one
DELETE FROM todo_list 
WHERE id = $1 AND user_id = $2
RETURNING id, project_id, user_id, title, description, completed, created_at, updated_at
`

type DeleteToDoByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteToDoByID(ctx context.Context, arg DeleteToDoByIDParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, deleteToDoByID, arg.ID, arg.UserID)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
