// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: DeleteProjectByID.sql

package db

import (
	"context"
)

const deleteProjectByID = `-- name: DeleteProjectByID :one
DELETE FROM projects_todo_list
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, created_at
`

type DeleteProjectByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteProjectByID(ctx context.Context, arg DeleteProjectByIDParams) (ProjectsTodoList, error) {
	row := q.db.QueryRow(ctx, deleteProjectByID, arg.ID, arg.UserID)
	var i ProjectsTodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
