// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: DeleteToDoByID.sql

package db

import (
	"context"
)

const deleteToDoByID = `-- name: DeleteToDoByID :one
DELETE FROM todo_list 
WHERE id = $1
RETURNING id, project_id, title, description, completed, created_at, updated_at
`

func (q *Queries) DeleteToDoByID(ctx context.Context, id int32) (TodoList, error) {
	row := q.db.QueryRow(ctx, deleteToDoByID, id)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
