// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetAllUser.sql

package db

import (
	"context"
)

const getAllUser = `-- name: GetAllUser :many
SELECT id, username, email 
FROM users
`

type GetAllUserRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) GetAllUser(ctx context.Context) ([]GetAllUserRow, error) {
	rows, err := q.db.Query(ctx, getAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserRow
	for rows.Next() {
		var i GetAllUserRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
