// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetPostByUserID.sql

package db

import (
	"context"
	"time"
)

const getPostByUserID = `-- name: GetPostByUserID :many
SELECT 
user_id, -- Will generate ` + "`" + `json:"user_id"` + "`" + `
title, -- Will generate ` + "`" + `json:"title"` + "`" + `
content -- Will generate ` + "`" + `json:"content"` + "`" + `
username -- Will generate ` + "`" + `json:"username"` + "`" + `
FROM text_posts
WHERE user_id = $1
AND created_at BETWEEN $2 AND $3
`

type GetPostByUserIDParams struct {
	UserID      int32     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetPostByUserIDRow struct {
	UserID   int32  `json:"user_id"`
	Title    string `json:"title"`
	Username string `json:"username"`
}

func (q *Queries) GetPostByUserID(ctx context.Context, arg GetPostByUserIDParams) ([]GetPostByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getPostByUserID, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostByUserIDRow
	for rows.Next() {
		var i GetPostByUserIDRow
		if err := rows.Scan(&i.UserID, &i.Title, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
