// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetTextPostsByTime.sql

package db

import (
	"context"
	"time"
)

const getTextPostsByTime = `-- name: GetTextPostsByTime :many
SELECT 
user_id, -- Will generate ` + "`" + `json:"user_id"` + "`" + `
title, -- Will generate ` + "`" + `json:"title"` + "`" + `
content -- Will generate ` + "`" + `json:"content"` + "`" + `
username -- Will generate ` + "`" + `json:"username"` + "`" + `
FROM text_posts
WHERE created_at BETWEEN $1
                    AND $2
`

type GetTextPostsByTimeParams struct {
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

type GetTextPostsByTimeRow struct {
	UserID   int32  `json:"user_id"`
	Title    string `json:"title"`
	Username string `json:"username"`
}

func (q *Queries) GetTextPostsByTime(ctx context.Context, arg GetTextPostsByTimeParams) ([]GetTextPostsByTimeRow, error) {
	rows, err := q.db.Query(ctx, getTextPostsByTime, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTextPostsByTimeRow
	for rows.Next() {
		var i GetTextPostsByTimeRow
		if err := rows.Scan(&i.UserID, &i.Title, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
