// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUserDataById.sql

package db

import (
	"context"
	"time"
)

const getUserDataById = `-- name: GetUserDataById :one
SELECT id, username, email, created_at
FROM users
WHERE id = $1
`

type GetUserDataByIdRow struct {
	ID        int32
	Username  string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) GetUserDataById(ctx context.Context, id int32) (GetUserDataByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserDataById, id)
	var i GetUserDataByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
