// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUserIDByToken.sql

package db

import (
	"context"
)

const getUserIDByToken = `-- name: GetUserIDByToken :one
SELECT user_id
FROM refresh_token
WHERE token = $1
`

func (q *Queries) GetUserIDByToken(ctx context.Context, token string) (int32, error) {
	row := q.db.QueryRow(ctx, getUserIDByToken, token)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
