// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUserPasswordWithEmail.sql

package db

import (
	"context"
)

const getUserPasswordWithEmail = `-- name: GetUserPasswordWithEmail :one
SELECT id,password
FROM users
WHERE email = $1
`

type GetUserPasswordWithEmailRow struct {
	ID       int32
	Password string
}

func (q *Queries) GetUserPasswordWithEmail(ctx context.Context, email string) (GetUserPasswordWithEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserPasswordWithEmail, email)
	var i GetUserPasswordWithEmailRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}
