// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUserDataById.sql

package db

import (
	"context"
)

const getUserDataById = `-- name: GetUserDataById :one
SELECT id, username, email
FROM users
WHERE id = $1
`

type GetUserDataByIdRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) GetUserDataById(ctx context.Context, id int32) (GetUserDataByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserDataById, id)
	var i GetUserDataByIdRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}
