// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUserProjectByUserID.sql

package db

import (
	"context"
	"time"
)

const getUserProjectByUserID = `-- name: GetUserProjectByUserID :many

SELECT 
id, -- Will generate ` + "`" + `json:"id"` + "`" + `
title, -- Will generate ` + "`" + `json:"title"` + "`" + `
created_at -- Will generate ` + "`" + `json:"created_at"` + "`" + `
FROM projects_todo_list
WHERE user_id = $1
`

type GetUserProjectByUserIDRow struct {
	ID        int32     `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserProjectByUserID(ctx context.Context, userID int32) ([]GetUserProjectByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getUserProjectByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserProjectByUserIDRow
	for rows.Next() {
		var i GetUserProjectByUserIDRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
