// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUsernameById.sql

package db

import (
	"context"
)

const getUsernameById = `-- name: GetUsernameById :one

SELECT username
FROM users
WHERE id = $1
`

func (q *Queries) GetUsernameById(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getUsernameById, id)
	var username string
	err := row.Scan(&username)
	return username, err
}
