// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUserToDoByProjectID.sql

package db

import (
	"context"
)

const getUserToDoByProjectID = `-- name: GetUserToDoByProjectID :many
SELECT
id, -- Will generate ` + "`" + `json:"id"` + "`" + `
title, -- Will generate ` + "`" + `json:"title"` + "`" + `
description, -- Will generate ` + "`" + `json:"description"` + "`" + `
completed -- Will generate ` + "`" + `json:"completed"` + "`" + `
FROM todo_list 
WHERE project_id = $1 AND user_id = $2
`

type GetUserToDoByProjectIDParams struct {
	ProjectID int32 `json:"project_id"`
	UserID    int32 `json:"user_id"`
}

type GetUserToDoByProjectIDRow struct {
	ID          int32  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Completed   bool   `json:"completed"`
}

func (q *Queries) GetUserToDoByProjectID(ctx context.Context, arg GetUserToDoByProjectIDParams) ([]GetUserToDoByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getUserToDoByProjectID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserToDoByProjectIDRow
	for rows.Next() {
		var i GetUserToDoByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
