// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUserWithEmail.sql

package db

import (
	"context"
)

const getUserWithEmail = `-- name: GetUserWithEmail :one
SELECT id, username, email, password
FROM users
WHERE email = $1
`

func (q *Queries) GetUserWithEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}
