// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: SetRefreshToken.sql

package db

import (
	"context"
)

const setRefreshToken = `-- name: SetRefreshToken :one
UPDATE refresh_token
SET token = $1
WHERE user_id = $2
RETURNING id, user_id, token
`

type SetRefreshTokenParams struct {
	Token  string
	UserID int32
}

func (q *Queries) SetRefreshToken(ctx context.Context, arg SetRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, setRefreshToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(&i.ID, &i.UserID, &i.Token)
	return i, err
}
