// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: UpdateCompleteToDo.sql

package db

import (
	"context"
)

const updateCompleteToDo = `-- name: UpdateCompleteToDo :one
UPDATE todo_list 
SET 
    completed = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, description, completed, created_at, updated_at
`

type UpdateCompleteToDoParams struct {
	ID        int32 `json:"id"`
	Completed bool  `json:"completed"`
}

func (q *Queries) UpdateCompleteToDo(ctx context.Context, arg UpdateCompleteToDoParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, updateCompleteToDo, arg.ID, arg.Completed)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
