openapi: 3.0.3

info:
  title: API Users Management
  version: 1.0.0

paths:
  /api/auth/registration:
    post:
      summary: Create user data

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref : "#/components/schemas/RegistrationRequest"


      responses:
        "201" :
          description: Created
          content:
            application/json:
              schema:
                $ref : "#/components/schemas/DefaultResponse"

  /api/auth/login:
    post:
      summary: User login

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref : "#/components/schemas/RegistrationRequest"
        
      responses:
        "200" :
          description: Success
          content:
            application/json:
                schema:
                  $ref : "#/components/schemas/DefaultResponse"

  /api/user/list:
    get:
      summary: List Users

      responses:
        "200":
          description: Success
          content:
            application/json:

              schema:
                items:
                  $ref : "#/components/schemas/ListUsersResponse"
              
              example:
                message: "success to fetch users"
                users:
                  - ID: 1
                    Email: dummy1@gmail.com
                    Username: dummy1
          
                  - ID: 2
                    Email: dummy2@gmail.com
                    Username: dummy2
          
                  - ID: 3
                    Email: dummy3@gmail.com
                    Username: dummy3


components:

  schemas:

    DefaultResponse:
      type: object
      properties:
        message: 
          type : string

    RegistrationRequest:
      type: object
      properties:
        Username:
          type: string
        Email:
          type: string
        Password: 
          type: string

    LoginRequest:
      type: object
      properties:
        Email: 
          type : string
        Passsword:
          type: string


    GetUserResponse:
      type: object
      properties:
        ID:
          type: integer
        Email: 
          type: string
        Username:
          type: string
    
    ListUsersResponse:
      type: object
      properties:
        message: 
          type: string
        users:
          type: array
          items:
            $ref : "#/components/schemas/GetUserResponse"



        


