openapi: 3.0.3

info:
  title: API Users Management
  version: 1.0.0

paths:
  /api/auth/registration:
    post:
      summary: Create user data

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref : "#/components/schemas/RegistrationRequest"


      responses:
        "201" :
          description: Created
          content:
            application/json:
              schema:
                $ref : "#/components/schemas/DefaultResponse"

  /api/auth/login:
    post:
      summary: User login

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref : "#/components/schemas/RegistrationRequest"
        
      responses:
        "200" :
          description: Success
          content:
            application/json:
                schema:
                  $ref : "#/components/schemas/DefaultResponse"

  /api/user/list:
    get:
      summary: List Users

      responses:
        "200":
          description: Success
          content:
            application/json:

              schema:
                items:
                  $ref : "#/components/schemas/ListUsersResponse"
              
              # example:
              #   message: "success to fetch users"
              #   users:
              #     - id: 1
              #       email: dummy1@gmail.com
              #       username: dummy1
          
              #     - id: 2
              #       email: dummy2@gmail.com
              #       username: dummy2
          
              #     - id: 3
              #       email: dummy3@gmail.com
              #       username: dummy3
  /api/user/{id}:
    get:
      summary: Fetch user data by id
      parameters:
        - name: id
          in: path
          required: true
          description: user id 
          schema:
            type: integer
          
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoResponse"
              # examples:
              #   user1:
              #     value:
              #       id: 1
              #       username: dummy1
              #       email: dummy1@gmail.com

components:

  schemas:

    DefaultResponse:
      type: object
      properties:
        message: 
          type : string

    RegistrationRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password: 
          type: string

    LoginRequest:
      type: object
      properties:
        email: 
          type : string
        passsword:
          type: string


    GetUserResponse:
      type: object
      properties:
        id:
          type: integer
        email: 
          type: string
        username:
          type: string
      
    UserInfoResponse:
      type: object
      properties:
        id:
          type: integer
        email: 
          type: string
        username:
          type: string
    
    ListUsersResponse:
      type: object
      properties:
        message: 
          type: string
        users:
          type: array
          items:
            $ref : "#/components/schemas/GetUserResponse"



        


