openapi: 3.2.0

info:
  title: API Users Management
  version: 1.0.0

paths:
  /api/auth/registration:
    post:
      summary: Create user data

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref : "#/components/schemas/RegistrationRequest"


      responses:
        "201" :
          description: Created
          content:
            application/json:
              schema:
                $ref : "#/components/schemas/DefaultResponse"

  /api/auth/login:
    post:
      summary: User login

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref : "#/components/schemas/RegistrationRequest"
        
      responses:
        "200" :
          description: Success
          content:
            application/json:
              schema:
                $ref : "#/components/schemas/DefaultResponse"

                

components:

  schemas:

    DefaultResponse:
      type: object
      properties:
        message: 
          type : string

    ReigstrationRequest:
      type: object
      properties:
        Username:
          type: string
        Email:
          type: string
        Password: 
          type: string

    LoginRequest:
      type: object
      properties:
        Email: 
          type : string
        Passsword:
          type: string


        


